### ISSUE TITLE
Recursion issue when using docker to load a scenario

### ISSUE THREAD

**Issue by Mingze-Li128** [Breakthrough-Energy/PowerSimData#615] opened 2022-04-14 13:29 UTC
### **Bug summary**
Trying to load a scenario by Scenario() with docker leads to maximum recursion depth exceeded.

###** Code for reproduction**

We create a scenario in docker land try to load it
```
from powersimdata import Scenario

from powersimdata import Scenario

scenario = Scenario()

print(scenario.state.name)
scenario.set_grid(grid_model="usa_tamu", interconnect="Western")
scenario.set_name("test", "rec")

scenario.set_time("2016-08-01 00:00:00", "2016-08-31 23:00:00", "24H")
scenario.set_base_profile("demand", "vJan2021")
scenario.set_base_profile("hydro", "vJan2021")
scenario.set_base_profile("solar", "vJan2021")
scenario.set_base_profile("wind", "vJan2021")
scenario.change_table.scale_plant_capacity(
  "solar", zone_name={"Washington": 5, "Arizona": 2.5})
scenario.change_table.scale_plant_capacity(
    "wind", zone_name={"Oregon": 1.5, "Montana Western": 2})
scenario.change_table.scale_branch_capacity(
    zone_name={"Nevada": 2, "Wyoming": 2})

scenario.change_table.add_branch(
    [{"capacity": 200, "from_bus_id": 2053002, "to_bus_id": 2053303},
     {"capacity": 150, "from_bus_id": 2060002, "to_bus_id": 2060046}])

scenario.change_table.add_dcline(
    [{"capacity": 2000, "from_bus_id": 2060771, "to_bus_id": 2021598}])
scenario.change_table.add_plant(
    [{"type": "solar", "bus_id": 2030454, "Pmax": 75},
     {"type": "coal", "bus_id": 2074334, "Pmin": 25, "Pmax": 750, "c0": 1800, "c1": 30, "c2": 0.0025},
     {"type": "ng", "bus_id": 2090018, "Pmax": 75, "c0": 900, "c1": 30, "c2": 0.0015}])
scenario.change_table.add_bus(
    [{"lat": 48, "lon": -125, "zone_id": 201, "baseKV": 138}])
scenario.change_table.add_dcline(
    [{"from_bus_id": 2090023, "to_bus_id": 2090024, "Pmin": 0, "Pmax": 200}])

grid = scenario.get_grid()

ct = scenario.get_ct()

scenario = Scenario("rec")
```
which lead to
```
RecursionError                            Traceback (most recent call last)
/tmp/ipykernel_49/697919857.py in <module>
      1 from powersimdata import Scenario
      2 
----> 3 scenario = Scenario("rec")
      4 # print scenario information
      5 scenario.print_scenario_info()

/usr/local/lib/python3.8/site-packages/powersimdata/scenario/scenario.py in __init__(self, descriptor)
     66                 self._set_status()
     67                 if state == "execute":
---> 68                     self.state = Execute(self)
     69                 elif state == "analyze":
     70                     self.state = Analyze(self)

/usr/local/lib/python3.8/site-packages/powersimdata/scenario/execute.py in __init__(self, scenario)
     31         """Constructor."""
     32         super().__init__(scenario)
---> 33         self.refresh(scenario)
     34 
     35     @property

/usr/local/lib/python3.8/site-packages/powersimdata/scenario/execute.py in refresh(self, scenario)
     54 
     55         self._set_ct_and_grid()
---> 56         self._launcher = Context.get_launcher(scenario)
     57 
     58     def _set_ct_and_grid(self):

/usr/local/lib/python3.8/site-packages/powersimdata/data_access/context.py in get_launcher(scenario)
     38             return SSHLauncher(scenario)
     39         elif mode == DeploymentMode.Container:
---> 40             return HttpLauncher(scenario)
     41         return NativeLauncher(scenario)

/usr/local/lib/python3.8/site-packages/powersimdata/data_access/launcher.py in __init__(self, scenario)
     47     def __init__(self, scenario):
     48         self.scenario = scenario
---> 49         self.scenario_id = scenario.scenario_id
     50 
     51     def _launch(self, threads=None, solver=None, extract_data=True):

/usr/local/lib/python3.8/site-packages/powersimdata/scenario/scenario.py in __getattr__(self, name)
     73 
     74     def __getattr__(self, name):
---> 75         if name in self.state.exported_methods:
     76             return getattr(self.state, name)
     77         elif hasattr(self.state, "__getattr__"):

... last 1 frames repeated, from the frame below ...

/usr/local/lib/python3.8/site-packages/powersimdata/scenario/scenario.py in __getattr__(self, name)
     73 
     74     def __getattr__(self, name):
---> 75         if name in self.state.exported_methods:
     76             return getattr(self.state, name)
     77         elif hasattr(self.state, "__getattr__"):

RecursionError: maximum recursion depth exceeded
```

### **Environment**
Please specify your platform and versions of the relevant libraries you are using:

Operating system: Windows 11
Docker & jupyter notebook
Gurobi version: 9.1.2

**Comment by danielolsen** [comment] 2022-04-14 16:13
From your error block, it seems like we're trying to load a `Scenario` which has been created (i.e. `Scenario.create_scenario()` has been called), so the Scenario is in `Execute` state, and there we get a recursion error, but I don't see this `create_scenario` step in your code. If you can reproduce this error, could you please post the full sequence of events that leads you to this it? You may need a new name to be passed to `scenario.set_name`. You can omit the `change_table` method calls since they don't seem to be significant to the error we're seeing.

**Comment by danielolsen** [comment] 2022-04-14 16:34
This seems like an issue that has been fixed since v0.4.5 (see #563, thanks @BainanXia). Could you run `pip list` from the shell which has access to the python environment in which you're encountering this error and report the version of `powersimdata` that you see? You can do this from within jupyter notebook by running `!pip list`.

**Comment by Mingze-Li128** [comment] 2022-04-14 16:57
> 
It seems that the powersimdata version in docker is 0.4.4
```
Name: powersimdata
Version: 0.4.4
Summary: Power Simulation Data
Home-page: https://github.com/Breakthrough-Energy/PowerSimData
Author: Kaspar Mueller
Author-email: kaspar@breakthroughenergy.org
License: UNKNOWN
Location: /usr/local/lib/python3.8/site-packages
Requires: fs.sshfs, numpy, pandas, networkx, fs, paramiko, tqdm, scipy, requests
Required-by: postreise
Note: you may need to restart the kernel to use updated packages.
```

**Comment by Mingze-Li128** [comment] 2022-04-14 17:07
> From your error block, it seems like we're trying to load a `Scenario` which has been created (i.e. `Scenario.create_scenario()` has been called), so the Scenario is in `Execute` state, and there we get a recursion error, but I don't see this `create_scenario` step in your code. If you can reproduce this error, could you please post the full sequence of events that leads you to this it? You may need a new name to be passed to `scenario.set_name`. You can omit the `change_table` method calls since they don't seem to be significant to the error we're seeing.

It seems that the powersimdata version in docker is 0.4.4

```
Name: powersimdata
Version: 0.4.4
Summary: Power Simulation Data
Home-page: https://github.com/Breakthrough-Energy/PowerSimData
Author: Kaspar Mueller
Author-email: kaspar@breakthroughenergy.org
License: UNKNOWN
Location: /usr/local/lib/python3.8/site-packages
Requires: fs.sshfs, numpy, pandas, networkx, fs, paramiko, tqdm, scipy, requests
Required-by: postreise
Note: you may need to restart the kernel to use updated packages.
```

**Comment by danielolsen** [comment] 2022-04-14 17:25
I would guess that the container you're using was built sometime between September 2021 and January 2022, when PowerSimData v0.4.4 was the latest version. If you run `docker build` again, it should grab the newest version of PowerSimData and solve this issue.

**Comment by jon-hagg** [comment] 2022-04-14 17:57
To ensure the image is up to date, I would try `docker pull ghcr.io/breakthrough-energy/powersimdata:latest`. The build command might work, but create a different image based on the local git repo (and depending on how it's tagged). However if you are using the compose files from [plug](https://github.com/Breakthrough-Energy/plug/tree/main/standalone) that is probably the `postreise:stable` image, which could also be updated using `docker pull`.

**Comment by dmuldrew** [comment] 2022-04-14 18:21
Also, if you are using `docker-compose` file, you can use the command `docker-compose pull` to pull down the latest images.

**Comment by Mingze-Li128** [comment] 2022-04-15 14:45
> I would guess that the container you're using was built sometime between September 2021 and January 2022, when PowerSimData v0.4.4 was the latest version. If you run `docker build` again, it should grab the newest version of PowerSimData and solve this issue.

I tried to upgrade PowerSimData to v0.4.5.  It seems we can load a scenario correctly.

However, when I tried to create a new scenario following the instruction by

```
scenario = Scenario()
print(scenario.state.name)

scenario.set_grid(interconnect="Western")
```

It returns
`CreateFailed: root path '/root/ScenarioData/raw/usa_tamu' does not exist`

I tried all versions from v0.4.5 to v0.5.0. All have this issue.

**Comment by jon-hagg** [comment] 2022-04-18 20:47
@Mingze-Li128 just want to check, are you using the compose files from [plug](https://github.com/Breakthrough-Energy/plug), in particular the [docker volume](https://github.com/Breakthrough-Energy/plug/blob/main/standalone/docker-compose.yml#L11)? I seem to be able to create a scenario using the `main` branch from there with no modifications.

**Comment by jon-hagg** [comment] 2022-04-18 21:10
Yeah, I'm seeing this error with v0.5.0. I believe it should be fixed in the next release, but you can also create the `usa_tamu` directory in that location to workaround it temporarily.

**Comment by jon-hagg** [comment] 2022-04-21 22:44
Specifically, both the latest and stable [postreise](https://github.com/Breakthrough-Energy/plug/pkgs/container/postreise) images should be fixed.

**Comment by danielolsen** [comment] 2022-05-12 19:04
This seems to be resolved, so I'm closing this issue.

**Closed by danielolsen** 2022-05-12 19:04 UTC
Labels: bug
