### ISSUE TITLE
Energy Storage Parameters

### ISSUE THREAD

**Issue by LFPower** [Breakthrough-Energy/PowerSimData#448] opened 2021-04-11 14:23 UTC
https://github.com/Breakthrough-Energy/PowerSimData/blob/74579a19eba274c52809c20bbf2510a896e7a6ba/powersimdata/input/change_table.py#L479

In the energy storage part, we also need to consider the maximum charging and discharging rate.
Here is my list {SOC_max, SOC_min, Pchr_max, Pdis_max, Charge Efficiency, Discharge Efficiency, Loss Factor,  Terminal Max, Terminal Min,  SOC_intial, MaxNumofCycles}.

I do not know, what does Energy_value represents?

**Comment by danielolsen** [comment] 2021-04-11 16:04
I think this information is part of #447.

**Comment by danielolsen** [comment] 2021-04-12 22:14
Closed at a duplicate of #447

**Closed by danielolsen** 2021-04-12 22:14 UTC
